"""Add trade_run and trade_leg tables

Revision ID: 79dfd3588839
Revises: 
Create Date: 2026-07-14 16:03:48.106154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79dfd3588839'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trade_run',
    sa.Column('ship', sa.String(), nullable=True),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trade_leg',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('leg_type', sa.Enum('ACQUISITION', 'SALE', name='leg_type'), nullable=False),
    sa.Column('terminal_name', sa.String(), nullable=False),
    sa.Column('commodity_name', sa.String(), nullable=False),
    sa.Column('quantity_scu', sa.Integer(), nullable=False),
    sa.Column('price_per_unit', sa.Integer(), nullable=False),
    sa.Column('cargo_transfer_type', sa.Enum('MANUAL', 'AUTOLOAD', name='cargo_transfer_type'), nullable=False),
    sa.Column('cargo_transfer_fee', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reached_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transaction_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transferred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['trade_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trade_leg')
    op.drop_table('trade_run')
    # ### end Alembic commands ###
