"""Add pilot_memory table

Revision ID: 882529c6f049
Revises: 
Create Date: 2026-07-10 14:35:52.260449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '882529c6f049'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pilot_memory',
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('classification', sa.Enum('CORRECTION', 'BEHAVIORAL_INSTRUCTION', 'PILOT_PREFERENCE', 'INCIDENTAL_DETAIL', 'EPISODIC_EVENT', name='memory_classification'), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('last_reinforced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pilot_memory')
    # ### end Alembic commands ###
