"""add uex_price_cache table

Revision ID: f9a456633928
Revises: 79dfd3588839
Create Date: 2026-07-15 16:59:02.162894

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f9a456633928'
down_revision: str | Sequence[str] | None = '79dfd3588839'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uex_price_cache',
    sa.Column('kind', sa.Enum('COMMODITY', 'TERMINAL', name='uex_cache_kind'), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('rows', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'entity_id', name='uq_uex_price_cache_kind_entity')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('uex_price_cache')
    # ### end Alembic commands ###
